CREATE TABLE IF NOT EXISTS `CFG_BUILDING` (
  `ID` INT NOT NULL,
  `NAME` varchar(40) COMMENT '中文名',
  `TYPE_NAME` varchar(40) COMMENT '英文名',
  `DESCRIPTION` varchar(200) COMMENT '',
  `PLACE` TINYINT COMMENT '0: 外 1:内',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `CFG_BUILDING_CONDITION` (
  `ID` INT NOT NULL,
  `BUILD_ID` INT COMMENT '',
  `LEVEL_ID` SMALLINT COMMENT '',
  `PRE_TYPE` TINYINT COMMENT '',
  `PRE_ID` TINYINT COMMENT '',
  `PRE_LEVEL` INT COMMENT '',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `CFG_BUILDING_LEVEL` (
  `ID` INT NOT NULL,
  `BUILD_ID` INT COMMENT '建筑ID',
  `LEVEL` SMALLINT COMMENT '建筑等级',
  `UPGRADE_WOOD` BIGINT COMMENT '消耗木材',
  `UPGRADE_ROCK` BIGINT COMMENT '消耗石头',
  `UPGRADE_IRON` BIGINT COMMENT '消耗铁定',
  `UPGRADE_FOOD` BIGINT COMMENT '消耗粮食',
  `UPGRADE_GOLD` BIGINT COMMENT '升级消耗金币',
  `UPGRADE_PEOPLE` INT COMMENT '升级依赖人口',
  `UPGRADE_TIME` BIGINT COMMENT '升级耗时',
  `USING_PEOPLE` BIGINT COMMENT '占用人口',
  `DESCRIPTION` varchar(1000) COMMENT '描述',
  `CREATE_TIME` bigint,
  `MODIFY_TIME` bigint,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;