CREATE TABLE IF NOT EXISTS `GI_GOODS` (
  `ID` INT NOT NULL COMMENT 'GI_PLAY.ID * 1000000 + CFG_GOODS.ID',
  `GOODS_ID` INT COMMENT '物品ID',
  `COUNT` INT COMMENT '数量',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `GI_CITY` (
  `ID` INT NOT NULL,
  `PLAY_ID` INT    COMMENT '',
  `NAME` varchar(200) DEFAULT  '新城池'  NOT NULL COMMENT '',
  `CITY_TYPE` TINYINT    COMMENT '类型0:玩家城池1:名城2:郡城3:州城4:都城5:玩家主城',
  `STATE` TINYINT    COMMENT '城池状态0：正常;1：新手保护;2：免战;3：休假',
  `CHIEFH_ID` INT    COMMENT '城守ID',
  `COUNSELLOR_ID` INT    COMMENT '军师ID',
  `GENERAL_ID` INT    COMMENT '将军ID',
  `COLLEGELV` SMALLINT DEFAULT  0   COMMENT '书院等级',
  `PROVINCE_ID` INT    COMMENT '城池所属州',
  `CONSCRIPT` TINYINT DEFAULT  0   COMMENT '否是可以募兵，0表示不可以，1表示可以，大于2，最后招募时间',
  `DISCARD_TIME` BIGINT    COMMENT '废弃时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GI_CITY_SOLDIER` (
  `ID` INT NOT NULL,
  `CITY_ID` INT COMMENT '城池ID',
  `SOLDIER_ID` INT COMMENT '士兵模版ID',
  `COUNT` BIGINT COMMENT '数量',
  `CUR_LEVEL` SMALLINT COMMENT '等级',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `GI_CITY_RESOURCE_ADD` (
  `ID` INT NOT NULL,
  `FOOD_RATE` TINYINT DEFAULT 80 COMMENT '粮食人口生产比例',
  `WOOD_RATE` TINYINT DEFAULT 80 COMMENT '木头人口生产比例',
  `ROCK_RATE` TINYINT DEFAULT 80 COMMENT '石材人口生产比例',
  `IRON_RATE` TINYINT DEFAULT 80 COMMENT '铁锭人口生产比例',
  `FOOD_STORE` BIGINT DEFAULT 0 COMMENT '仓库存放粮食数量',
  `WOOD_STORE` BIGINT DEFAULT 0 COMMENT '仓库存木头食数量',
  `ROCK_STORE` BIGINT DEFAULT 0 COMMENT '仓库存石材食数量',
  `IRON_STORE` BIGINT DEFAULT 0 COMMENT '仓库存铁锭食数量',
  `FOOD_FIELD_ADD` BIGINT DEFAULT 0 COMMENT '野地对粮食加成',
  `WOOD_FIELD_ADD` BIGINT DEFAULT 0 COMMENT '野地对木头加成',
  `ROCK_FIELD_ADD` BIGINT DEFAULT 0 COMMENT '野地对石材加成',
  `IRON_FIELD_ADD` BIGINT DEFAULT 0 COMMENT '野地对铁锭加成',
  `FOOD_GOODS_ADD` BIGINT DEFAULT 0 COMMENT '物品对粮食加成',
  `WOOD_GOODS_ADD` BIGINT DEFAULT 0 COMMENT '物品对木头加成',
  `ROCK_GOODS_ADD` BIGINT DEFAULT 0 COMMENT '物品对石材加成',
  `IRON_GOODS_ADD` BIGINT DEFAULT 0 COMMENT '物品对铁锭加成',
  `CHIEF_ADD` BIGINT DEFAULT 0 COMMENT '将领加成',
  `FOOD_SKILL_ADD` BIGINT DEFAULT 0 COMMENT '科技对粮食加成',
  `WOOD_SKILL_ADD` BIGINT DEFAULT 0 COMMENT '科技对木头加成',
  `ROCK_SKILL_ADD` BIGINT DEFAULT 0 COMMENT '科技对石材加成',
  `IRON_SKILL_ADD` BIGINT DEFAULT 0 COMMENT '科技对铁锭加成',
  `RESOURCE_CHANGE` TINYINT DEFAULT 0 COMMENT '资源是否发生过变化',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `GI_CITY_RESOURCE` (
  `ID` INT NOT NULL,
  `MORALE` TINYINT DEFAULT 80 COMMENT '当前民心',
  `MORALE_STABLE` TINYINT DEFAULT 80 COMMENT '民心稳定值',
  `COMPLAINT` TINYINT DEFAULT 0 COMMENT '民怨',
  `TAX` TINYINT DEFAULT 20 COMMENT '税率',
  `WOOD` BIGINT DEFAULT 10000 COMMENT '库存木材',
  `WOOD_ADD` BIGINT DEFAULT 10000 COMMENT '木材产量',
  `WOOD_MAX` BIGINT DEFAULT 10000 COMMENT '木材上限',
  `ROCK` BIGINT DEFAULT 10000 COMMENT '库存石材',
  `ROCK_ADD` BIGINT DEFAULT 10000 COMMENT '石材产量',
  `ROCK_MAX` BIGINT DEFAULT 10000 COMMENT '石材上限',
  `IRON` BIGINT DEFAULT 10000 COMMENT '库存铁锭',
  `IRON_ADD` BIGINT DEFAULT 10000 COMMENT '铁锭产量',
  `IRON_MAX` BIGINT DEFAULT 10000 COMMENT '铁锭上限',
  `FOOD` BIGINT DEFAULT 10000 COMMENT '库存粮食',
  `FOOD_ADD` BIGINT DEFAULT 10000 COMMENT '粮食产量',
  `FOOD_ARMY_USE` BIGINT DEFAULT 0 COMMENT '军队耗粮食',
  `FOOD_MAX` BIGINT DEFAULT 10000 COMMENT '粮食上限',
  `GOLD` BIGINT DEFAULT 1000000 COMMENT '库存黄金',
  `HERO_FEE` BIGINT DEFAULT 0 COMMENT '将领薪水',
  `GOLD_MAX` BIGINT DEFAULT 1000000 COMMENT '黄金上限',
  `GOLD_RATE` TINYINT DEFAULT 20 COMMENT '黄金产量分倍率',
  `PEOPLE` BIGINT DEFAULT 100 COMMENT '当前总人口',
  `PEOPLE_STABLE` BIGINT DEFAULT 100 COMMENT '人口稳定值',
  `PEOPLE_WORKING` BIGINT DEFAULT 0 COMMENT '工作耗人口',
  `PEOPLE_BUILDING` BIGINT DEFAULT 0 COMMENT '建筑人口',
  `PEOPLE_MAX` BIGINT DEFAULT 100 COMMENT '人口最大值',
  `CHIEF_LOYALTY` SMALLINT DEFAULT 0 COMMENT '首领忠诚??',
  `CHANGING` BIGINT DEFAULT 0 COMMENT '',
  `LAST_UPDATE` BIGINT DEFAULT 0 COMMENT '',
  `VACATION` TINYINT DEFAULT 0 COMMENT '０表示正常，１表示休假',
  `FORBIDDEN` TINYINT DEFAULT 0 COMMENT '０表示正常，１表示封禁',
  `AUTO_BUILDING` TINYINT DEFAULT 0 COMMENT '自动建筑',
  `AUTO_TECHNIC` TINYINT DEFAULT 0 COMMENT '自动科技',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `GI_CITY_DEFENCE` (
  `ID` INT NOT NULL,
  `CITY_ID` INT COMMENT '玩家ID',
  `DEFENCE_ID` INT COMMENT '城防ID',
  `COUNT` BIGINT COMMENT '数量',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `GI_CITY_BUILD` (
  `ID` INT NOT NULL,
  `CITY_ID` INT COMMENT '城池ID',
  `BID` INT COMMENT '建筑ID',
  `POS` TINYINT COMMENT '建筑位置',
  `LV` SMALLINT COMMENT '建筑等级',
  `STATUS` TINYINT DEFAULT 0 COMMENT '0:正常,1:升级中,2:降级',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;