CREATE TABLE IF NOT EXISTS `MEM_CITY_BUILD_UPGRADING` (
      `ID` INT NOT NULL   COMMENT 'GI_BUILD id',
      `PLAY_ID` INT    COMMENT '',
      `CITY_ID` INT    COMMENT '',
      `STATUS` TINYINT DEFAULT  0   COMMENT ':升级中,2:降级',
      `GOAL_LV` TINYINT DEFAULT  1   COMMENT '目标等级',
      `END_TIME` BIGINT    COMMENT '结束时间',
      PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `MEM_TECHNIC_UPGRADING` (
  `ID` INT NOT NULL,
  `PLAY_ID` INT COMMENT '',
  `CITY_ID` INT COMMENT '',
  `TECHNIC_ID` INT COMMENT '',
  `START_TIME` BIGINT COMMENT '开始时间',
  `END_TIME` BIGINT COMMENT '结束时间',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `MEM_WORLD_TILE` (
  `ID` INT NOT NULL,
  `TILE_TYPE` TINYINT COMMENT '格子地型：0:城池;1:平地;2:沙漠;3:森林;4:草地;5:高山;6:湖泊;7:沼泽;',
  `PROVINCE` TINYINT COMMENT '州',
  `JUN` TINYINT COMMENT '郡',
  `CUR_LEVEL` SMALLINT COMMENT '当前等级',
  `MAX_LEVEL` SMALLINT COMMENT '最大等级',
  `OWNER_CITY_ID` BIGINT COMMENT '所属城池',
  `STATE` TINYINT COMMENT '当前状态',
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;