CREATE TABLE IF NOT EXISTS `SYS_PRIMARY_KEY` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` varchar(100) NOT NULL COMMENT '表名字',
    `CUR_VALUE` BIGINT NOT NULL COMMENT '当前值',
    `VERSION` BIGINT NOT NULL COMMENT '当前获取次数',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `SYS_USER` (
    `ID` INT NOT NULL,
    `LOGIN_CODE` varchar(200) COMMENT '登录名称',
    `PASSWORD` varchar(200) COMMENT '密码',
    `QQ_NO` varchar(200) COMMENT 'qq号',
    `ADMIN_FLAG` INT COMMENT '1为管理员,0为普通用户',
    `STATUS` INT COMMENT '1为正常,2未激活,3锁定,0删除',
    `LAST_LOGIN_TIME` BIGINT COMMENT '最后登录时间!',
    `LAST_TOKEN` varchar(200) COMMENT '最后登录Token!',
    `LAST_IP` varchar(200) COMMENT '最后登录Ip!',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `SYS_USER_LOG` (
    `ID` INT NOT NULL,
    `ACTION` INT COMMENT '1登录,2登出',
    `REMARK` varchar(500) COMMENT '内容',
    `TOKEN` varchar(200) COMMENT '最后登录Token!',
    `IP` varchar(200) COMMENT '最后登录Ip!',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE IF NOT EXISTS `MEM_WORLD_TILE` (
    `ID` INT NOT NULL,
    `TILE_TYPE` TINYINT COMMENT '格子地型：0:城池;1:平地;2:沙漠;3:森林;4:草地;5:高山;6:湖泊;7:沼泽;',
    `PROVINCE` TINYINT COMMENT '州',
    `JUN` TINYINT COMMENT '郡',
    `CUR_LEVEL` SMALLINT COMMENT '当前等级',
    `MAX_LEVEL` SMALLINT COMMENT '最大等级',
    `OWNER_CITY_ID` BIGINT COMMENT '所属城池',
    `STATE` TINYINT COMMENT '当前状态',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;


CREATE TABLE IF NOT EXISTS `GI_PLAYER` (
  `ID` INT NOT NULL,
  `NAME` varchar(200)    COMMENT '名字',
  `STATE` SMALLINT    COMMENT '玩家状态 0: 正常,1 新手,2 免战玩家,4: 被打完主城的玩家',
  `PLAYER_GROUP` SMALLINT    COMMENT '玩家组 0:正常玩家 1:GM 2: NPC',
  `GENDER` SMALLINT    COMMENT '性别 1:男 2:女',
  `LAST_CITY` BIGINT    COMMENT '君主将最后所在城池',
  `FACE` varchar(100)    COMMENT '脸ID',
  `FLAG_CHAR` varchar(40)    COMMENT '旗帜名称',
  `PLAYER_RANK` SMALLINT    COMMENT '排名',
  `PRESTIGE` BIGINT    COMMENT '声望',
  `WAR_PRESTIGE` BIGINT    COMMENT '战场获得声望',
  `WAR_ATTACK_PRESTIGE` BIGINT    COMMENT '战争进攻获得声望',
  `WAR_DEFENCE_PRESTIGE` BIGINT    COMMENT '战争防御获得声望',
  `NOBILITY` SMALLINT    COMMENT '爵位等级',
  `OFFICEPOS` SMALLINT    COMMENT '官职',
  `UNION_ID` BIGINT    COMMENT '联盟ID',
  `UNION_POS` SMALLINT    COMMENT '联盟职位',
  `MONEY` BIGINT    COMMENT '元宝',
  `ARMOR_COLUMN` SMALLINT    COMMENT '用户的装备栏数量',
  `VIP_LEVEL` SMALLINT    COMMENT 'vip等级',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `GI_CITY` (
  `ID` INT NOT NULL,
  `PLAY_ID` INT    COMMENT '',
  `NAME` varchar(200) DEFAULT  '新城池'  NOT NULL COMMENT '',
  `CITY_TYPE` TINYINT    COMMENT '类型0:玩家城池1:名城2:郡城3:州城4:都城5:玩家主城',
  `STATE` TINYINT    COMMENT '城池状态0：正常;1：新手保护;2：免战;3：休假',
  `CHIEFH_ID` INT    COMMENT '',
  `COUNSELLOR_ID` INT    COMMENT '',
  `PROVINCE_ID` INT    COMMENT '',
  `CONSCRIPT` TINYINT DEFAULT  0   COMMENT '否是可以募兵，0表示不可以，1表示可以，大于2，最后招募时间',
  `DISCARD_TIME` BIGINT  DEFAULT  0    COMMENT '废弃时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `GI_CITY_RESOURCE_ADD` (
  `ID` INT NOT NULL,
  `FOOD_RATE` TINYINT DEFAULT  80   COMMENT '粮食人口生产比例',
  `WOOD_RATE` TINYINT DEFAULT  80   COMMENT '木头人口生产比例',
  `ROCK_RATE` TINYINT DEFAULT  80   COMMENT '石材人口生产比例',
  `IRON_RATE` TINYINT DEFAULT  80   COMMENT '铁锭人口生产比例',
  `FOOD_STORE` BIGINT DEFAULT  0   COMMENT '仓库存放粮食数量',
  `WOOD_STORE` BIGINT DEFAULT  0   COMMENT '仓库存木头食数量',
  `ROCK_STORE` BIGINT DEFAULT  0   COMMENT '仓库存石材食数量',
  `IRON_STORE` BIGINT DEFAULT  0   COMMENT '仓库存铁锭食数量',
  `FOOD_FIELD_ADD` BIGINT DEFAULT  0   COMMENT '野地对粮食加成',
  `WOOD_FIELD_ADD` BIGINT DEFAULT  0   COMMENT '野地对木头加成',
  `ROCK_FIELD_ADD` BIGINT DEFAULT  0   COMMENT '野地对石材加成',
  `IRON_FIELD_ADD` BIGINT DEFAULT  0   COMMENT '野地对铁锭加成',
  `FOOD_GOODS_ADD` BIGINT DEFAULT  0   COMMENT '物品对粮食加成',
  `WOOD_GOODS_ADD` BIGINT DEFAULT  0   COMMENT '物品对木头加成',
  `ROCK_GOODS_ADD` BIGINT DEFAULT  0   COMMENT '物品对石材加成',
  `IRON_GOODS_ADD` BIGINT DEFAULT  0   COMMENT '物品对铁锭加成',
  `CHIEF_ADD` BIGINT DEFAULT  0   COMMENT '将领加成',
  `FOOD_SKILL_ADD` BIGINT DEFAULT  0   COMMENT '科技对粮食加成',
  `WOOD_SKILL_ADD` BIGINT DEFAULT  0   COMMENT '科技对木头加成',
  `ROCK_SKILL_ADD` BIGINT DEFAULT  0   COMMENT '科技对石材加成',
  `IRON_SKILL_ADD` BIGINT DEFAULT  0   COMMENT '科技对铁锭加成',
  `RESOURCE_CHANGE` TINYINT DEFAULT  0   COMMENT '资源是否发生过变化',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS `GI_CITY_RESOURCE` (
  `ID` INT NOT NULL,
  `MORALE` TINYINT    COMMENT '当前民心',
  `MORALE_STABLE` TINYINT    COMMENT '民心稳定值',
  `COMPLAINT` TINYINT    COMMENT '民怨',
  `TAX` TINYINT    COMMENT '税率',
  `WOOD` BIGINT    COMMENT '库存木材',
  `WOOD_ADD` BIGINT    COMMENT '木材产量',
  `WOOD_MAX` BIGINT    COMMENT '木材上限',
  `ROCK` BIGINT    COMMENT '库存石材',
  `ROCK_ADD` BIGINT    COMMENT '石材产量',
  `ROCK_MAX` BIGINT    COMMENT '石材上限',
  `IRON` BIGINT    COMMENT '库存铁锭',
  `IRON_ADD` BIGINT    COMMENT '铁锭产量',
  `IRON_MAX` BIGINT    COMMENT '铁锭上限',
  `FOOD` BIGINT    COMMENT '库存粮食',
  `FOOD_ADD` BIGINT    COMMENT '粮食产量',
  `FOOD_ARMY_USE` BIGINT    COMMENT '军队耗粮食',
  `FOOD_MAX` BIGINT    COMMENT '粮食上限',
  `GOLD` BIGINT    COMMENT '库存黄金',
  `HERO_FEE` BIGINT    COMMENT '将领薪水',
  `GOLD_MAX` BIGINT    COMMENT '黄金上限',
  `GOLD_RATE` TINYINT    COMMENT '黄金产量分倍率',
  `PEOPLE` BIGINT    COMMENT '当前总人口',
  `PEOPLE_STABLE` BIGINT    COMMENT '人口稳定值',
  `PEOPLE_WORKING` BIGINT    COMMENT '工作耗人口',
  `PEOPLE_BUILDING` BIGINT    COMMENT '建筑人口',
  `PEOPLE_MAX` BIGINT    COMMENT '人口最大值',
  `CHIEF_LOYALTY` SMALLINT    COMMENT '首领忠诚??',
  `CHANGING` BIGINT    COMMENT '',
  `LAST_UPDATE` BIGINT    COMMENT '',
  `VACATION` TINYINT    COMMENT '０表示正常，１表示休假',
  `FORBIDDEN` TINYINT    COMMENT '０表示正常，１表示封禁',
  `AUTO_BUILDING` TINYINT    COMMENT '自动建筑',
  `AUTO_TECHNIC` TINYINT    COMMENT '自动科技',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `GI_CITY_DEFENCE` (
  `ID` INT NOT NULL,
  `CITY_ID` INT    COMMENT '玩家ID',
  `DEFENCE_ID` INT    COMMENT '城防ID',
  `COUNT` BIGINT    COMMENT '数量',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS `GI_CITY_BUILD` (
  `ID` INT NOT NULL,
  `CITY_ID` INT    COMMENT '城池ID',
  `BID` INT    COMMENT '建筑ID',
  `POS` TINYINT    COMMENT '建筑位置',
  `LV` SMALLINT    COMMENT '建筑等级',
  `STATUS` TINYINT DEFAULT  0   COMMENT '0:正常,1:升级中,2:降级',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS `GI_CITY_HERO` (
  `ID` INT NOT NULL,
  `PLAY_ID` INT    COMMENT '归属哪个玩家，如果是NPC的话，为0',
  `NPC_ID` INT    COMMENT '所属npcId,如果是玩家,为0',
  `CITY_ID` INT    COMMENT '',
  `NAME` varchar(200) DEFAULT  '新城池'  NOT NULL COMMENT '',
  `CITY_TYPE` TINYINT DEFAULT  0   COMMENT '类型0:玩家城池1:名城2:郡城3:州城4:都城5:玩家主城',
  `STATE` TINYINT DEFAULT  0   COMMENT '状态：0，空闲；1,城守；2,出征，3,战斗,4，驻守,5,俘虏',
  `GENDER` TINYINT  NOT NULL COMMENT '1男:2女',
  `FACE` INT    COMMENT '',
  `HERO_TYPE` TINYINT    COMMENT '将领类型,0普通武将，1黄巾活动武将,2聚贤包开出武将,3-9圣诞武将，1001-1005',
  `HERO_HEALTH` TINYINT DEFAULT  0   COMMENT '状态：0，健康；1，重伤；2，修养',
  `LEVEL` SMALLINT    COMMENT '级别',
  `EXP` BIGINT DEFAULT  0   COMMENT '经验值',
  `COMMAND_BASE` SMALLINT    COMMENT '领将的统率',
  `COMMAND_ADD_ON` SMALLINT    COMMENT '率统加成',
  `AFFAIRS_BASE` SMALLINT    COMMENT '内政',
  `BRAVERY_BASE` SMALLINT    COMMENT '勇武',
  `WISDOM_BASE` SMALLINT    COMMENT '智谋',
  `AFFAIRS_ADD` SMALLINT    COMMENT '内政加点',
  `BRAVERY_ADD` SMALLINT    COMMENT '勇武加点',
  `WISDOM_ADD` SMALLINT    COMMENT '智谋加点',
  `AFFAIRS_ADD_ON` BIGINT    COMMENT '政内加成',
  `BRAVERY_ADD_ON` BIGINT    COMMENT '勇武加成',
  `WISDOM_ADD_ON` BIGINT    COMMENT '智谋加成',
  `FORCE_MAX_ADD_ON` SMALLINT    COMMENT '体力加成',
  `ENERGY_MAX_ADD_ON` SMALLINT    COMMENT '精力加成',
  `SPEED_ADD_ON` SMALLINT    COMMENT '速度加成',
  `ATTACK_ADD_ON` BIGINT    COMMENT '攻击加成',
  `DEFENCE_ADD_ON` BIGINT    COMMENT '防御加成',
  `LOYALTY` SMALLINT    COMMENT '忠诚',
  `CREATE_TIME` bigint ,
  `MODIFY_TIME` bigint ,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

